## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/clover-api/*"
  to = "http://server.wzc520pyf.cn/api/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
