// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import "@vue/runtime-core";

export {};

declare module "@vue/runtime-core" {
  export interface GlobalComponents {
    AdminLayout: typeof import("./../components/common/AdminLayout.vue")["default"];
    BetterScroll: typeof import("./../components/custom/BetterScroll.vue")["default"];
    DarkModeContainer: typeof import("./../components/common/DarkModeContainer.vue")["default"];
    ElAvatar: typeof import("element-plus/es")["ElAvatar"];
    ElBreadcrumb: typeof import("element-plus/es")["ElBreadcrumb"];
    ElBreadcrumbItem: typeof import("element-plus/es")["ElBreadcrumbItem"];
    ElConfigProvider: typeof import("element-plus/es")["ElConfigProvider"];
    ElDropdown: typeof import("element-plus/es")["ElDropdown"];
    ElDropdownItem: typeof import("element-plus/es")["ElDropdownItem"];
    ElDropdownMenu: typeof import("element-plus/es")["ElDropdownMenu"];
    ElementProvider: typeof import("./../components/common/ElementProvider.vue")["default"];
    ElIcon: typeof import("element-plus/es")["ElIcon"];
    ElMenu: typeof import("element-plus/es")["ElMenu"];
    ElMenuItem: typeof import("element-plus/es")["ElMenuItem"];
    ElMenuItemGroup: typeof import("element-plus/es")["ElMenuItemGroup"];
    ElScrollbar: typeof import("element-plus/es")["ElScrollbar"];
    ElSubMenu: typeof import("element-plus/es")["ElSubMenu"];
    ElTabPane: typeof import("element-plus/es")["ElTabPane"];
    ElTabs: typeof import("element-plus/es")["ElTabs"];
    ElTooltip: typeof import("element-plus/es")["ElTooltip"];
    ExceptionBase: typeof import("./../components/common/ExceptionBase.vue")["default"];
    HelloWorld: typeof import("./../components/HelloWorld.vue")["default"];
    HoverContainer: typeof import("./../components/common/HoverContainer.vue")["default"];
    IconCommunity: typeof import("./../components/icons/IconCommunity.vue")["default"];
    IconDocumentation: typeof import("./../components/icons/IconDocumentation.vue")["default"];
    IconEcosystem: typeof import("./../components/icons/IconEcosystem.vue")["default"];
    IconLogo: typeof import("./../components/icons/IconLogo.vue")["default"];
    IconSupport: typeof import("./../components/icons/IconSupport.vue")["default"];
    IconTooling: typeof import("./../components/icons/IconTooling.vue")["default"];
    IEpExpand: typeof import("~icons/ep/expand")["default"];
    IEpFold: typeof import("~icons/ep/fold")["default"];
    IEpFullScreen: typeof import("~icons/ep/full-screen")["default"];
    IEpRefreshRight: typeof import("~icons/ep/refresh-right")["default"];
    IMdiGithub: typeof import("~icons/mdi/github")["default"];
    IMdiMoonWaningCrescent: typeof import("~icons/mdi/moon-waning-crescent")["default"];
    IMdiWhiteBalanceSunny: typeof import("~icons/mdi/white-balance-sunny")["default"];
    Loading: typeof import("./../components/business/Loading.vue")["default"];
    RouterLink: typeof import("vue-router")["RouterLink"];
    RouterView: typeof import("vue-router")["RouterView"];
    TheWelcome: typeof import("./../components/TheWelcome.vue")["default"];
    WelcomeItem: typeof import("./../components/WelcomeItem.vue")["default"];
  }
}
